### ISSUE TITLE
rasa server is not working!!!

### ISSUE THREAD

**Issue by EdukondaluK** [navigateconsulting/virtual-assistant#158]
all containers are working fine except rasa server.

**Comment by EdukondaluK** [comment]
even logs are not detecting,kindly help on it.

**Comment by EdukondaluK** [comment]
have followed all steps in the document for docker-compose build and up and rest 2 commands which are used to progress in UI. where i have seen docker ps -a 

all containers are working fine except rasa/rasa:1.3.1-full . it has shown that  exited 132.
actions server,
mogodatabase,
api gateway and ui trainer all are working good.

thanks and regards,
Edukondalu

**Comment by saikiran2603** [comment]
Hi @EdukondaluK  which operating system are you trying it on ?

**Comment by saikiran2603** [comment]
also could you show docker compose logs when you get exited 132 error ?

**Comment by EdukondaluK** [comment]
![image](https://user-images.githubusercontent.com/18613739/72078900-fb386000-331f-11ea-8833-41b39bc53e73.png)

I have been tried to see logs but didnt get.
kindly help how to debug.. I have tried to put DEBUG_MODE:"true" not detecting in the rasa server image lines

**Comment by saikiran2603** [comment]
sure , could you try below commands , 

shut down all running containers 
`$ docker-compose down `

start the containers again with attached mode (skip the -d argument in the command) so that you can see the logs. 
`$ docker-compose up`

Now you would see all the logs on your screen. dont close the terminal window and try to reproduce the issue. once you see the error message (exited 132) in the terminal logs , copy those logs and paste them here

**Comment by saikiran2603** [comment]
also have you modified the docker-compose file ? if yes could you post its contents here ?

**Comment by EdukondaluK** [comment]
it was due to python version...
